name: goes2go
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - git
  - rclone >= 1.58.0  # Not required by goes2go, but is an awesome alternative https://rclone.org/

  # Tools
  # -----
  - cartopy
  - geopandas
  - h5netcdf
  - jupyter
  - jupyterlab
  - matplotlib
  - metpy
  - netcdf4
  - numpy
  - pandas
  - s3fs
  - toml
  - xarray

  # Formatter & Testing
  # -------------------
  - black
  - isort
  - pytest


  # Documentation
  # -------------
  - sphinx
  - nbsphinx
  - pydata-sphinx-theme # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
  - sphinx-design
  - recommonmark
  - sphinx-markdown-tables
  - autodocsumm
  - sphinx-autosummary-accessors # pandas and xarray accessor docs
  - latexmk
  - myst-parser
  - linkify-it-py

  - pip:
      # Install from PyPi
      #- goes2go
      # * or install most recent version on GitHub
      - git+https://github.com/blaylockbk/goes2go.git

      # Borrow some tools from my garage
      - git+https://github.com/blaylockbk/Carpenter_Workshop.git

###############################################################################
#
# Note: Being more specific with versions *may* help speed up conda
# creating/updating environments
# https://www.anaconda.com/blog/understanding-and-improving-condas-performance
#
###############################################################################
#
# To create this environment
#
#     wget https://github.com/blaylockbk/goes2go/raw/main/environment.yml
#     conda env create -f environment.yml
#
# To update this environment
#
#     conda env update -f environment.yml --prune
#
# To remove this environment
#
#     conda env remove --name environment
#
###############################################################################
