name: goes2go
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - git
  - rclone >= 1.58.0  # Not required by goes2go, but is an awesome alternative https://rclone.org/

  # Tools
  # -----
  - cartopy >= 0.20.2
  - geopandas >= 0.10.2
  - h5netcdf >= 0.15.0
  - jupyter >= 1.0.0
  - jupyterlab >= 3.3.2
  - matplotlib >= 3.5.1
  - metpy >= 1.2.0
  - netcdf4 >= 1.5.8
  - numpy >= 1.22.3
  - pandas >= 1.4.1
  - s3fs >= 2022.2.0
  - toml >= 0.10.2
  - xarray >= 2022.3.0

  # Formatter & Testing
  # -------------------
  - black >= 22.1.0
  - jupyterlab_code_formatter
  - isort >= 5.10.1
  - pytest >= 7.1.1


  # Documentation
  # -------------
  - sphinx >= 4.4.0
  - nbsphinx
  - pydata-sphinx-theme # PyData Sphinx Theme (i.e, Numpy, Pandas, MetPy)
  - sphinx-panels # Add bootstrap elements to Sphinx
  - recommonmark
  - sphinx-markdown-tables
  - autodocsumm
  - sphinx-autosummary-accessors # pandas and xarray accessor docs
  - latexmk
  - myst-parser
  - linkify-it-py

  - pip:
      # Install from PyPi
      #- goes2go
      # * or install most recent version on GitHub
      - git+https://github.com/blaylockbk/goes2go.git

      # Borrow some tools from my garage
      - git+https://github.com/blaylockbk/Carpenter_Workshop.git

###############################################################################
#
# Note: Being more specific with versions *may* help speed up conda
# creating/updating environments
# https://www.anaconda.com/blog/understanding-and-improving-condas-performance
#
###############################################################################
#
# To create this environment
#
#     wget https://github.com/blaylockbk/goes2go/raw/main/environment.yml
#     conda env create -f environment.yml
#
# To update this environment
#
#     conda env update -f environment.yml --prune
#
# To remove this environment
#
#     conda env remove --name environment
#
###############################################################################
